spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:                                   # H2는 기본 비번 없음 (비워도 됨)
  jpa:
    defer-datasource-initialization: true       # data.sql 초기화 필요시 사용
    hibernate:
      ddl-auto: create                          # 엔티티 기반 테이블 자동 생성/업데이트
  h2:
    console:
      enabled: true                             # 웹 콘솔 사용 가능 http://localhost:8080/h2-console
  sql:
    init:
      mode: always                              # 애플리케이션 실행 시 항상 실행되게 함
      encoding: UTF-8




